# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
@EXPLICIT
https://repo.continuum.io/pkgs/main/linux-64/blas-1.0-mkl.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/ca-certificates-2018.4.16-0.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/intel-openmp-2018.0.0-8.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/libgcc-ng-7.2.0-hdf63c60_3.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/libgfortran-ng-7.2.0-hdf63c60_3.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/libstdcxx-ng-7.2.0-hdf63c60_3.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/libffi-3.2.1-hd88cf55_4.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/libgcc-7.2.0-h69d50b8_2.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/mkl-2018.0.2-1.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/ncurses-6.1-hf484d3e_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/openssl-1.0.2o-0.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/tk-8.6.7-hc745277_3.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/xz-5.2.4-h14c3975_4.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/zlib-1.2.11-ha838bed_2.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/libedit-3.1.20170329-h6b74fdf_2.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/readline-7.0-ha6073c6_4.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/sqlite-3.23.1-he433501_0.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/python-3.6.5-hc3d631a_2.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/alabaster-0.7.10-py36h306e16b_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/asn1crypto-0.24.0-py36_0.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/backcall-0.1.0-py36_0.tar.bz2
https://conda.anaconda.org/dsm/linux-64/blpapi-3.9.0-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/certifi-2018.4.16-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/chardet-3.0.4-py36h0f667ec_1.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/decorator-4.3.0-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/docutils-0.14-py36hb0f60f5_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/idna-2.6-py36h82fb2a8_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/imagesize-1.0.0-py36_0.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/ipython_genutils-0.2.0-py36hb52b0d5_0.tar.bz2
https://repo.anaconda.com/pkgs/free/linux-64/joblib-0.11-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/markupsafe-1.0-py36hd9260cd_1.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/numpy-base-1.14.3-py36h9be14a7_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/parso-0.2.1-py36_0.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/pickleshare-0.7.4-py36h63277f8_0.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/ptyprocess-0.5.2-py36h69acd42_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pycparser-2.18-py36hf9f622e_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pyparsing-2.2.0-py36hee85983_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pysocks-1.6.8-py36_0.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/pytz-2018.4-py36_0.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/simplegeneric-0.8.1-py36_2.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/six-1.11.0-py36h372c433_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/snowballstemmer-1.2.1-py36h6febd40_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/sphinxcontrib-1.0-py36h6d0f590_1.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/wcwidth-0.1.7-py36hdf4376a_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/babel-2.6.0-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/cffi-1.11.5-py36h9745a5d_0.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/jedi-0.12.0-py36_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/packaging-17.1-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pexpect-4.6.0-py36_0.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/python-dateutil-2.7.3-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/setuptools-39.2.0-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/sphinxcontrib-websupport-1.0.1-py36hb5cb234_1.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/traitlets-4.3.2-py36h674d592_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/cryptography-2.2.2-py36h14c3975_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/ghp-import-0.5.5-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/jinja2-2.10-py36ha16c418_0.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/pygments-2.2.0-py36h0d3125c_0.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/wheel-0.31.1-py36_0.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/pip-10.0.1-py36_0.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/prompt_toolkit-1.0.15-py36h17d85b1_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pyopenssl-18.0.0-py36_0.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/ipython-6.4.0-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/urllib3-1.22-py36hbe7ace6_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/requests-2.18.4-py36he2e5f8d_1.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/sphinx-1.7.5-py36_0.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/mkl_fft-1.0.1-py36h3010b51_0.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/mkl_random-1.0.1-py36h629b387_0.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/numpy-1.14.3-py36hcd700cb_1.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/pandas-0.23.0-py36h637b7d7_0.tar.bz2
